### PR TITLE
fix: only delete ttfs during otf conversion

### LINKED ISSUE #3: When converting ttf files the original ttf is deleted after the conversion
The fix in #2 deletes any `.ttf` file in the directory after conversion instead of just targeting `.ttf` files created during `.otf` conversion

### PR DESCRIPTION
**Pull request by tikagan**
- [x] only delete ttf font files during otf conversion
- [x] keeps track of ttf file generated during otf conversion instead of finding it again later (re: [this comment](https://github.com/undone-labs/fontpls/pull/2#discussion_r1464092406)) 

Fixes UL-51

### CODE REVIEW

**Comment by orvn** [comment]
Thanks, I'll give this a test!

File: converter.js [hunk 1]
```diff
@@ -31,11 +31,8 @@ export function convertFont(inputPath) {
         console.error('Error during conversion:', err);
         return;
       }
-      const ttfFile = files.find((file, i) => {
-        return file.path.includes('ttf', (file.path.length - 3))
-      })
-      if (ttfFile) {
-        fs.unlink(ttfFile.path, err => { if (err) { console.log('Error during ttf file removal: ', err) }})
+      if (deleteTtf) {
+        fs.unlink(input.path, err => { if (err) { console.log('Error during ttf file removal: ', err) }})
```
Comment (orvn) [inline converter.js]: Let's use `console.error()` for this bit instead of just logging it

**Review by orvn — CHANGES_REQUESTED** [review]
Looks good except for a minor change! @tikagan
